## **KNN**

In [0]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from sklearn import datasets

In [0]:
iris=datasets.load_iris()

In [0]:
X=iris.data

In [0]:
y=iris.target

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=20)

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [0]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)

In [0]:
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred=classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[6 0 0]
 [0 2 3]
 [0 1 8]]


In [0]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.67      0.40      0.50         5
           2       0.73      0.89      0.80         9

    accuracy                           0.80        20
   macro avg       0.80      0.76      0.77        20
weighted avg       0.79      0.80      0.78        20

